stages:
  - test
  - build
  - deploy_dev
  - deploy_prod

variables:
  IMAGE_NAME: "registry.gitlab.com/miulina/doctor-clinic-devops-system"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"

test:
  stage: test
  tags:
    - local
  script:
    - copy .env.example .env
    - composer install --no-interaction --prefer-dist --optimize-autoloader
    - npm install
    - npm run build
    - php artisan key:generate
    - php artisan test
  only:
    - main
    - dev
    - merge_requests

build:
  stage: build
  tags:
    - local
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - main
    - dev

deploy_dev:
  stage: deploy_dev
  tags:
    - local
  script:
    - helm upgrade --install doctor-clinic-dev ./helm/doctor-clinic -n doctor-clinic-dev --create-namespace -f ./helm/doctor-clinic/values-dev.yaml --set image.repository=$IMAGE_NAME --set image.tag=$IMAGE_TAG
  only:
    - dev

deploy_prod:
  stage: deploy_prod
  tags:
    - local
  script:
    - helm upgrade --install doctor-clinic-prod ./helm/doctor-clinic -n doctor-clinic-prod --create-namespace -f ./helm/doctor-clinic/values-prod.yaml --set image.repository=$IMAGE_NAME --set image.tag=$IMAGE_TAG
  only:
    - main
  when: manual