stages:
  - test
  - build

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/doctor-clinic-app"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"

test:
  stage: test
  tags:
    - docker
    - ci
  script:
    - docker --version
    - docker run --rm php:8.2-cli php -v
    - docker run --rm composer:2 composer --version
  only:
    - dev
    - main

build:
  stage: build
  tags:
    - docker
    - ci
  script:
    - docker --version
    - echo "$env:CI_REGISTRY_PASSWORD" | docker login -u "$env:CI_REGISTRY_USER" "$env:CI_REGISTRY" --password-stdin
    - docker build -t "$env:CI_REGISTRY_IMAGE/doctor-clinic-app:$env:CI_COMMIT_SHORT_SHA" .
    - docker push "$env:CI_REGISTRY_IMAGE/doctor-clinic-app:$env:CI_COMMIT_SHORT_SHA"
  only:
    - dev
    - main