apiVersion: batch/v1
kind: Job
metadata:
  name: doctor-clinic-migrate
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["php", "artisan", "migrate", "--force"]
          env:
            - name: DB_HOST
              value: {{ .Values.app.env.DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.app.env.DB_PORT | quote }}
            - name: DB_DATABASE
              value: {{ .Values.app.env.DB_DATABASE | quote }}
            - name: DB_USERNAME
              value: {{ .Values.app.env.DB_USERNAME | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: doctor-clinic-secret
                  key: DB_PASSWORD
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: doctor-clinic-secret
                  key: APP_KEY