namespace: doctor-clinic-prod

app:
  replicaCount: 2
  env:
    APP_ENV: production
    APP_DEBUG: "false"
    APP_URL: "http://doctor-clinic-web"
    DB_HOST: "mysql"
    DB_PORT: "3306"
    DB_DATABASE: "doctors_prod"
    DB_USERNAME: "doctors_user"

mysql:
  database: "doctors_prod"
  user: "doctors_user"
  
secret:
  APP_KEY: "base64:prod-change-me"
  DB_PASSWORD: "prod-password"
  MYSQL_ROOT_PASSWORD: "prod-root-password"

persistence:
  size: 5Gi