namespace: doctor-clinic-dev

app:
  replicaCount: 1
  env:
    APP_ENV: development
    APP_DEBUG: "true"
    APP_URL: "http://doctor-clinic-web"
    DB_HOST: "mysql"
    DB_PORT: "3306"
    DB_DATABASE: "doctors_dev"
    DB_USERNAME: "doctors_user"

mysql:
  database: "doctors_dev"

secret:
  APP_KEY: "base64:dev-change-me"
  DB_PASSWORD: "dev-password"
  MYSQL_ROOT_PASSWORD: "dev-root-password"

persistence:
  size: 2Gi