namespace: doctor-clinic-prod

app:
  replicaCount: 2
  env:
    APP_ENV: production
    APP_DEBUG: "false"
    APP_URL: "http://doctor-clinic-web"
    DB_HOST: "mysql"
    DB_PORT: "3306"
    DB_DATABASE: "doctors_prod"
    DB_USERNAME: "doctors_user"

mysql:
  database: "doctors_prod"

dbImport:
  enabled: false

migrate:
  enabled: false

secret:
  APP_KEY: ""
  DB_PASSWORD: ""
  MYSQL_ROOT_PASSWORD: ""

persistence:
  size: 5Gi