namespace: default

image:
  repository: ""
  tag: latest
  pullPolicy: IfNotPresent

app:
  replicaCount: 1
  env:
    APP_NAME: "Doctor Clinic"
    APP_ENV: local
    APP_DEBUG: "true"
    APP_URL: "http://localhost"
    DB_CONNECTION: "mysql"
    DB_HOST: "mysql"
    DB_PORT: "3306"
    DB_DATABASE: "doctors_db"
    DB_USERNAME: "doctors_user"

service:
  web:
    type: ClusterIP
    port: 80
    targetPort: 80

php:
  targetPort: 9000

mysql:
  image: "mysql:8.0"
  port: 3306
  database: "doctors_db"
  username: "doctors_user"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 2Gi

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: doctor-clinic.local
      paths:
        - path: /
          pathType: Prefix
  tls: []